import { Cloud, DatabaseBackup, FolderCog, FolderOpen, HardHat, ListTree, PanelsTopLeft, RefreshCw, RotateCcw, ShieldCheck, Unplug } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useAsync } from '../hooks/useAsync'
import SyncSettings from '../components/SyncSettings'
import StorageServerSettings from '../components/StorageServerSettings'
import { Button, Card, PageHeader } from '../components/ui'

export default function SettingsPage(){
  const boot=useAsync(()=>window.fluxoDre.app.bootstrap(),[])
  const online=useAsync(()=>window.fluxoDre.online.state(),[])
  const [message,setMessage]=useState('')
  const [onlineUrl,setOnlineUrl]=useState('')
  useEffect(()=>{if(online.data?.baseUrl)setOnlineUrl(online.data.baseUrl)},[online.data?.baseUrl])
  const saveOnlineUrl=async()=>{setMessage('Salvando endpoint online...');try{await window.fluxoDre.online.setBaseUrl(onlineUrl);await online.reload();setMessage('Endpoint online salvo. Se o endereço mudou, o vínculo anterior foi removido por segurança.')}catch(error:any){setMessage(error.message)}}
  const connectOnline=async()=>{setMessage('Abrindo autorização do Desktop no navegador...');try{await window.fluxoDre.online.start();await online.reload();setMessage('Autorize este computador no navegador e depois clique em Verificar autorização.')}catch(error:any){setMessage(error.message)}}
  const checkOnline=async()=>{setMessage('Verificando autorização...');try{const status=await window.fluxoDre.online.status();await online.reload();setMessage(status.linked?'Desktop vinculado com sucesso. Agora você pode testar a conexão online.':'A autorização ainda está pendente.')}catch(error:any){setMessage(error.message)}}
  const testOnline=async()=>{setMessage('Testando conexão online...');try{const session=await window.fluxoDre.online.session();setMessage(`Conexão online ativa${session?.company?.name?` — ${session.company.name}`:''}.`);await online.reload()}catch(error:any){setMessage(error.message)}}
  const disconnectOnline=async()=>{try{await window.fluxoDre.online.disconnect();await online.reload();window.location.reload()}catch(error:any){setMessage(error.message)}}
  const changeLayout=async(layout:'command-center'|'classic')=>{if(layout===boot.data?.layout)return;setMessage('Aplicando layout...');try{await window.fluxoDre.app.setLayout(layout);window.location.reload()}catch(error:any){setMessage(error.message)}}
  const action=async(fn:()=>Promise<any>,success:string)=>{setMessage('Processando...');try{const result=await fn();setMessage(result?success:'Operação cancelada.');await boot.reload()}catch(error:any){setMessage(error.message)}}
  return <>
    <PageHeader title="Configurações" description="Dados locais, conectividade, pastas, backup, produto e manutenção do aplicativo."/>
    <div className="settings-grid">
      <SyncSettings/>
      <StorageServerSettings onMessage={setMessage}/>
      <Card className="setting-card"><DatabaseBackup size={21} color="#2f67d8"/><h3>Backup manual</h3><p>Cria uma cópia consistente do SQLite em uma pasta escolhida.</p><Button onClick={()=>action(()=>window.fluxoDre.backup.create(),'Backup criado com sucesso.')}>Criar backup</Button></Card>
      <Card className="setting-card"><RotateCcw size={21} color="#d89317"/><h3>Restaurar banco</h3><p>Salva uma cópia de segurança antes de substituir o banco atual.</p><Button variant="secondary" onClick={()=>action(()=>window.fluxoDre.backup.restore(),'Banco restaurado. Reinicie o aplicativo.')}>Restaurar</Button></Card>
      <Card className="setting-card setting-card-feature"><FolderCog size={21} color="#159a76"/><h3>Pasta da documentação</h3><p className="path-text">{boot.data?.documentsPath||'Carregando localização...'}</p><div className="setting-actions"><Button onClick={()=>action(()=>window.fluxoDre.documentos.chooseRoot(),'Pasta definida e estrutura espelhada.')}>Escolher pasta</Button><Button variant="secondary" icon={<FolderOpen size={15}/>} onClick={()=>window.fluxoDre.documentos.openFolder()}>Abrir</Button></div><small>Todas as empresas, colaboradores e subpastas serão criados neste local.</small></Card>
      <Card className="setting-card setting-card-feature"><Cloud size={21} color="#2f67d8"/><h3>Conexão Obra na Mão</h3><p>{online.data?.linked?'Este Desktop está vinculado ao ambiente online configurado.':online.data?.pending?'Aguardando autorização pelo navegador.':'Vincule este computador para testar sincronização, financeiro integrado e dados online.'}</p><span className={`status ${online.data?.linked?'status-success':''}`}>{online.data?.linked?'Online vinculado':online.data?.pending?'Autorização pendente':'Não vinculado'}</span><div style={{marginTop:10}}><input value={onlineUrl} onChange={e=>setOnlineUrl(e.target.value)} placeholder="https://seu-projeto.workers.dev" style={{width:'100%'}}/><div className="setting-actions" style={{marginTop:8}}><Button variant="secondary" onClick={saveOnlineUrl}>Salvar endpoint</Button></div></div><div className="setting-actions" style={{marginTop:10}}>{!online.data?.linked&&!online.data?.pending&&<Button onClick={connectOnline}>Vincular computador</Button>}{online.data?.pending&&<Button icon={<RefreshCw size={15}/>} onClick={checkOnline}>Verificar autorização</Button>}{online.data?.linked&&<><Button onClick={testOnline}>Testar conexão</Button><Button variant="secondary" icon={<Unplug size={15}/>} onClick={disconnectOnline}>Desconectar</Button></>}</div><small>{online.data?.baseUrl||'Carregando endpoint...'}</small></Card>
      <Card className="setting-card"><ShieldCheck size={21} color="#159a76"/><h3>Segurança local</h3><p>Context isolation ativo, renderer sem Node e banco restrito ao processo principal.</p><span className="status status-success">Proteções ativas</span></Card>
      <Card className="setting-card"><HardHat size={21} color="#2f67d8"/><h3>Edicao do produto</h3><p>{boot.data?.product?.edition==='empreiteira'?'Gestao obra empreiteira: medicoes como receita e margem por frente.':'Gestao obras construtora: foco em custo, contratado, pago e saldo por frente.'}</p><div className="setting-actions"><Button variant={boot.data?.product?.edition==='construtora'?'primary':'secondary'} onClick={()=>action(()=>window.fluxoDre.product.setEdition('construtora'),'Edicao Construtora aplicada.')}>Construtora</Button><Button variant={boot.data?.product?.edition==='empreiteira'?'primary':'secondary'} onClick={()=>action(()=>window.fluxoDre.product.setEdition('empreiteira'),'Edicao Empreiteira aplicada.')}>Empreiteira</Button></div></Card>
      <Card className="setting-card"><PanelsTopLeft size={21} color="#7c5ce0"/><h3>Layout da interface</h3><p>{boot.data?.layout==='classic'?'Visual tradicional, com a navegacao e as telas originais.':'Visual Command Center, com painel operacional escuro e navegacao compacta.'}</p><div className="setting-actions"><Button variant={boot.data?.layout!=='classic'?'primary':'secondary'} onClick={()=>changeLayout('command-center')}>Command Center</Button><Button variant={boot.data?.layout==='classic'?'primary':'secondary'} onClick={()=>changeLayout('classic')}>Classico</Button></div><small>A troca preserva os dados e recarrega somente a interface.</small></Card>
      <Card className="setting-card"><ListTree size={21} color="#2f67d8"/><h3>Dados ficticios</h3><p>Cria uma obra demo com hidraulica, prumadas, checklist por pavimento, medicao, contrato, compras, RDO e pendencias.</p><Button onClick={()=>action(()=>window.fluxoDre.demo.seed(),'Dados ficticios carregados. Abra Obras, Frentes ou Medicoes para visualizar.')}>Carregar demo</Button></Card>
    </div>

    {message&&<div className="success-box" style={{marginTop:14}}>{message}</div>}
    <Card style={{marginTop:14}}><div className="card-header"><h2>Informações técnicas</h2><ListTree size={17}/></div><div className="card-body form-grid"><div><small>Versão</small><strong style={{display:'block'}}>{boot.data?.version||'1.0.0'}</strong></div><div><small>Banco de dados</small><strong className="path-text" style={{display:'block'}}>{boot.data?.databasePath}</strong></div></div></Card>

  </>
}
