type Role='admin'|'foreman'|'employee';
type Member={id:string;email:string;name?:string;role:Role;employeeId?:string;userId?:string;joinCode?:string;modules?:string[];channels?:string[]};
type Access={modules:string[];channels:string[]};
type Device={id:string;name:string;platform?:string;email?:string;status:'active'|'revoked';lastSeenAt?:string;installationId?:string};
type SyncStatus={serverRevision:number;desktopRevision:number;conflictCount:number;lastServerUpdateAt?:string|null;lastDesktopPushAt?:string|null;lastDesktopSeenAt?:string|null;activeDevices:number;revokedDevices:number;devices:Device[]};

const MODULE_LABELS:Record<string,string>={finance:'Financeiro',rh:'RH',contracts:'Contratos',rdo:'RDO',obra360:'Obra360',dre:'DRE',procurement:'Compras',measurements:'Medições',documents:'Documentos',universidade:'Universidade',ai:'IA'};
const CHANNEL_LABELS:Record<string,string>={desktop:'Desktop',mobile:'Mobile'};
const ROLE_DEFAULTS:Record<Role,{modules:string[];channels:string[]}>={admin:{modules:Object.keys(MODULE_LABELS),channels:['desktop','mobile']},foreman:{modules:['obra360','rdo'],channels:['mobile']},employee:{modules:['obra360'],channels:['mobile']}};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char] as string));
const roleLabel=(role:Role)=>role==='admin'?'Admin':role==='foreman'?'Encarregado':'Funcionário';
const formatDateTime=(value?:string|null)=>{if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})};
const apiError=(error:unknown)=>{const value=error as {response?:{data?:{error?:string;message?:string}};message?:string};return value.response?.data?.error||value.response?.data?.message||value.message||'Não foi possível concluir a operação.'};
const dialog=()=>document.getElementById('sheet') as HTMLDialogElement|null;

function toast(message:string){const element=document.getElementById('toast');if(!element)return;element.textContent=message;element.classList.add('show');window.setTimeout(()=>element.classList.remove('show'),2400)}
function bindClose(dlg:HTMLDialogElement){dlg.querySelector('.close')?.addEventListener('click',()=>dlg.close())}
function showDialog(dlg:HTMLDialogElement,html:string){dlg.innerHTML=html;if(!dlg.open)dlg.showModal();bindClose(dlg)}
function badges(values:string[],labels:Record<string,string>){return values.map(value=>`<span class="badge released governance-badge">${esc(labels[value]||value)}</span>`).join('')||'<span class="meta">Nenhum</span>'}
function checkboxGroup(kind:'module'|'channel',values:string[],selected:string[]){const labels=kind==='module'?MODULE_LABELS:CHANNEL_LABELS;return `<div class="governance-check-grid">${values.map(value=>`<label class="governance-check"><input type="checkbox" data-gov-${kind}="${esc(value)}" value="${esc(value)}" ${selected.includes(value)?'checked':''}><span>${esc(labels[value]||value)}</span></label>`).join('')}</div>`}
function injectStyles(){if(document.getElementById('admin-governance-style'))return;const style=document.createElement('style');style.id='admin-governance-style';style.textContent=`
#adminGovernanceCard .governance-actions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:14px}
#adminGovernanceCard .governance-action{text-align:left;min-height:76px}#adminGovernanceCard .governance-action strong,#adminGovernanceCard .governance-action span{display:block}#adminGovernanceCard .governance-action span{font-size:12px;opacity:.78;margin-top:4px}
.governance-check-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:8px}.governance-check{display:flex;gap:8px;align-items:center;border:1px solid var(--line);border-radius:10px;padding:10px;font-size:13px}
.governance-member,.governance-device{display:grid;gap:8px}.governance-badges{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.governance-badge{font-size:11px}.governance-member-actions,.governance-device-actions{display:flex;justify-content:flex-end;gap:8px}
.governance-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:12px 0}.governance-metrics .metric strong{font-size:20px}.governance-health{display:grid;gap:10px}.governance-health-line{display:flex;justify-content:space-between;gap:16px;align-items:center}
@media(max-width:640px){#adminGovernanceCard .governance-actions,.governance-metrics{grid-template-columns:1fr}.governance-check-grid{grid-template-columns:1fr}.governance-health-line{align-items:flex-start;flex-direction:column;gap:3px}}
`;document.head.appendChild(style)}

function injectGovernanceCard(){if(window.multiuserContext?.role!=='admin')return;const headings=[...document.querySelectorAll('.section-head h2')];if(!headings.some(node=>node.textContent?.trim()==='Configurações'))return;document.getElementById('multiuserAdminCard')?.remove();if(document.getElementById('adminGovernanceCard'))return;injectStyles();const section=document.createElement('section');section.id='adminGovernanceCard';section.className='card settings-card';section.innerHTML=`<div class="section-head"><div><strong>Acessos e sincronização</strong><p>Controle permissões, computadores autorizados e o estado da integração Desktop ↔ Obra360.</p></div></div><div class="governance-actions"><button id="governancePermissionsBtn" class="linkbtn governance-action"><strong>Usuários e permissões</strong><span>Módulos e canais por pessoa</span></button><button id="governanceDevicesBtn" class="linkbtn governance-action"><strong>Computadores autorizados</strong><span>Revogar ou reativar acesso</span></button><button id="governanceSyncBtn" class="linkbtn governance-action"><strong>Saúde da sincronização</strong><span>Revisões, conflitos e atividade</span></button></div>`;document.getElementById('content')?.appendChild(section);section.querySelector('#governancePermissionsBtn')?.addEventListener('click',()=>void openPermissions());section.querySelector('#governanceDevicesBtn')?.addEventListener('click',()=>void openDevices());section.querySelector('#governanceSyncBtn')?.addEventListener('click',()=>void openSyncHealth())}

function moduleSelection(dlg:HTMLDialogElement){return [...dlg.querySelectorAll<HTMLInputElement>('[data-gov-module]:checked')].map(input=>input.value)}
function channelSelection(dlg:HTMLDialogElement){return [...dlg.querySelectorAll<HTMLInputElement>('[data-gov-channel]:checked')].map(input=>input.value)}
function applyDefaults(dlg:HTMLDialogElement,role:Role,access:Access){const defaults=ROLE_DEFAULTS[role];dlg.querySelectorAll<HTMLInputElement>('[data-gov-module]').forEach(input=>input.checked=defaults.modules.includes(input.value)&&access.modules.includes(input.value));dlg.querySelectorAll<HTMLInputElement>('[data-gov-channel]').forEach(input=>input.checked=defaults.channels.includes(input.value)&&access.channels.includes(input.value))}

async function openPermissions(edit?:Member){
  const dlg=dialog();if(!dlg)return;showDialog(dlg,'<div class="sheet"><div class="sheet-head"><div><h2>Usuários e permissões</h2><div class="meta">Carregando acessos da obra…</div></div><button class="close">×</button></div></div>');
  try{
    const data=(await window.appClient.api.get<{members:Member[];companyAccess:Access}>('/api/members')).data,members=data.members||[],access={modules:data.companyAccess?.modules||[],channels:data.companyAccess?.channels||[]};
    const employees=(window.multiuserContext?.projectState?.employees||[]) as Array<Record<string,unknown>>,editing=edit||undefined,initialRole=(editing?.role||'employee') as Role;
    const selectedModules=editing?.modules?.length?editing.modules:ROLE_DEFAULTS[initialRole].modules.filter(value=>access.modules.includes(value)),selectedChannels=editing?.channels?.length?editing.channels:ROLE_DEFAULTS[initialRole].channels.filter(value=>access.channels.includes(value));
    showDialog(dlg,`<div class="sheet"><div class="sheet-head"><div><h2>Usuários e permissões</h2><div class="meta">Cada acesso fica limitado também pelo plano contratado pela empresa.</div></div><button class="close">×</button></div><div class="members-list">${members.map(member=>`<div class="card governance-member" data-member-id="${esc(member.id)}"><div><strong>${esc(member.email)}</strong><div class="meta">${roleLabel(member.role)}${member.employeeId?` · ${esc(String(employees.find(employee=>employee.id===member.employeeId)?.name||member.employeeId))}`:''} · ${member.userId?'Ativo':`Aguardando login · Código ${esc(member.joinCode||'—')}`}</div><div class="governance-badges">${badges(member.modules||[],MODULE_LABELS)}${badges(member.channels||[],CHANNEL_LABELS)}</div></div><div class="governance-member-actions"><button type="button" class="linkbtn governance-edit-member" data-email="${esc(member.email)}">Editar</button></div></div>`).join('')||'<div class="empty card">Nenhum usuário cadastrado.</div>'}</div><div class="form member-form"><label>Email<input id="govMemberEmail" type="email" value="${esc(editing?.email||'')}" placeholder="nome@empresa.com" ${editing?'readonly':''}></label><label>Papel<select id="govMemberRole"><option value="employee" ${initialRole==='employee'?'selected':''}>Funcionário</option><option value="foreman" ${initialRole==='foreman'?'selected':''}>Encarregado</option><option value="admin" ${initialRole==='admin'?'selected':''}>Admin</option></select></label><label id="govEmployeeLinkLabel">Vincular ao funcionário<select id="govMemberEmployee"><option value="">Selecione</option>${employees.map(employee=>`<option value="${esc(employee.id)}" ${editing?.employeeId===employee.id?'selected':''}>${esc(employee.name)}</option>`).join('')}</select></label><div><div class="form-label">Módulos permitidos</div>${checkboxGroup('module',access.modules,selectedModules)}</div><div><div class="form-label">Canais permitidos</div>${checkboxGroup('channel',access.channels,selectedChannels)}</div></div><button id="saveGovMemberBtn" class="btn">Salvar acesso e permissões</button></div>`);
    const role=dlg.querySelector('#govMemberRole') as HTMLSelectElement,employeeLabel=dlg.querySelector('#govEmployeeLinkLabel') as HTMLElement;const toggleEmployee=()=>employeeLabel.style.display=role.value==='employee'?'block':'none';role.addEventListener('change',()=>{toggleEmployee();applyDefaults(dlg,role.value as Role,access)});toggleEmployee();
    dlg.querySelectorAll<HTMLButtonElement>('.governance-edit-member').forEach(button=>button.addEventListener('click',()=>{const member=members.find(item=>item.email===button.dataset.email);if(member)void openPermissions(member)}));
    dlg.querySelector('#saveGovMemberBtn')?.addEventListener('click',async()=>{const email=(dlg.querySelector('#govMemberEmail') as HTMLInputElement).value.trim(),memberRole=role.value as Role,employeeId=(dlg.querySelector('#govMemberEmployee') as HTMLSelectElement).value||undefined,modules=moduleSelection(dlg),channels=channelSelection(dlg);if(!email)return toast('Informe o e-mail.');if(memberRole==='employee'&&!employeeId)return toast('Vincule o funcionário deste acesso.');if(!modules.length)return toast('Selecione ao menos um módulo.');if(!channels.length)return toast('Selecione ao menos um canal.');try{await window.appClient.api.post('/api/members',{email,role:memberRole,employeeId,modules,channels});toast('Acesso e permissões salvos.');await openPermissions()}catch(error){toast(apiError(error))}});
  }catch(error){toast(apiError(error))}
}

function renderDevice(device:Device){const active=device.status==='active';return `<div class="card governance-device" data-device-id="${esc(device.id)}"><div class="row"><div><strong>${esc(device.name||'Computador')}</strong><div class="meta">${esc(device.platform||'Plataforma não informada')}${device.email?` · ${esc(device.email)}`:''}</div><div class="meta">Última atividade: ${esc(formatDateTime(device.lastSeenAt))}</div></div><span class="badge ${active?'completed':'blocked'}">${active?'Ativo':'Revogado'}</span></div><div class="governance-device-actions"><button class="${active?'linkbtn':'btn'}" data-device-action="${active?'revoke':'activate'}">${active?'Revogar acesso':'Reativar'}</button></div></div>`}
async function openDevices(){const dlg=dialog();if(!dlg)return;showDialog(dlg,'<div class="sheet"><div class="sheet-head"><div><h2>Computadores autorizados</h2><div class="meta">Carregando dispositivos da empresa…</div></div><button class="close">×</button></div></div>');try{const data=(await window.appClient.api.get<{devices:Device[]}>('/api/mobile/admin/devices')).data,devices=data.devices||[];showDialog(dlg,`<div class="sheet"><div class="sheet-head"><div><h2>Computadores autorizados</h2><div class="meta">Revogar um computador encerra apenas o acesso daquele dispositivo; a licença da empresa permanece ativa.</div></div><button class="close">×</button></div><div id="governanceDeviceList">${devices.map(renderDevice).join('')||'<div class="empty card">Nenhum computador vinculado.</div>'}</div></div>`);dlg.querySelectorAll<HTMLElement>('[data-device-id]').forEach(row=>{const button=row.querySelector<HTMLButtonElement>('[data-device-action]');button?.addEventListener('click',async()=>{const status=button.dataset.deviceAction==='revoke'?'revoked':'active';button.disabled=true;try{await window.appClient.api.put(`/api/mobile/admin/devices/${encodeURIComponent(String(row.dataset.deviceId||''))}`,{status});toast(status==='revoked'?'Computador revogado.':'Computador reativado.');await openDevices()}catch(error){button.disabled=false;toast(apiError(error))}})})}catch(error){toast(apiError(error))}}

function healthTone(conflicts:number){return conflicts>0?['Atenção','blocked']:['Sem conflitos','completed']}
async function openSyncHealth(){const dlg=dialog();if(!dlg)return;showDialog(dlg,'<div class="sheet"><div class="sheet-head"><div><h2>Saúde da sincronização</h2><div class="meta">Carregando estado do servidor e dos computadores…</div></div><button class="close">×</button></div></div>');try{const status=(await window.appClient.api.get<SyncStatus>('/api/mobile/admin/sync-status')).data,[toneLabel,tone]=healthTone(Number(status.conflictCount||0));showDialog(dlg,`<div class="sheet"><div class="sheet-head"><div><h2>Saúde da sincronização</h2><div class="meta">Os números de revisão do estado Web e do fluxo Desktop são contadores independentes; use datas e conflitos para diagnosticar a operação.</div></div><button class="close">×</button></div><div class="governance-metrics"><div class="metric"><span>Estado Web</span><strong>Servidor ${Number(status.serverRevision||0)}</strong></div><div class="metric"><span>Fluxo Desktop</span><strong>Desktop ${Number(status.desktopRevision||0)}</strong></div><div class="metric"><span>Conflitos abertos</span><strong>${Number(status.conflictCount||0)} conflito${Number(status.conflictCount||0)===1?'':'s'}</strong></div></div><div class="card governance-health"><div class="governance-health-line"><strong>Situação</strong><span class="badge ${tone}">${toneLabel}</span></div><div class="governance-health-line"><span>Última alteração Web</span><strong>${esc(formatDateTime(status.lastServerUpdateAt))}</strong></div><div class="governance-health-line"><span>Último lote recebido do Desktop</span><strong>${esc(formatDateTime(status.lastDesktopPushAt))}</strong></div><div class="governance-health-line"><span>Último computador visto</span><strong>${esc(formatDateTime(status.lastDesktopSeenAt))}</strong></div><div class="governance-health-line"><span>Computadores</span><strong>${Number(status.activeDevices||0)} ativo(s) · ${Number(status.revokedDevices||0)} revogado(s)</strong></div></div><section class="section"><div class="section-head"><div><h2>Atividade por computador</h2><p>Último contato conhecido de cada Desktop vinculado à empresa.</p></div></div>${(status.devices||[]).map(device=>`<div class="card governance-device"><div class="row"><div><strong>${esc(device.name)}</strong><div class="meta">${esc(device.platform||'')} · ${esc(formatDateTime(device.lastSeenAt))}</div></div><span class="badge ${device.status==='active'?'completed':'blocked'}">${device.status==='active'?'Ativo':'Revogado'}</span></div></div>`).join('')||'<div class="empty card">Nenhum computador vinculado.</div>'}</section><button id="refreshGovernanceSync" class="linkbtn" style="width:100%">Atualizar diagnóstico</button></div>`);dlg.querySelector('#refreshGovernanceSync')?.addEventListener('click',()=>void openSyncHealth())}catch(error){toast(apiError(error))}}

document.addEventListener('field:rendered',injectGovernanceCard);
