import { PORTUGUESE_VARIANTS } from './portuguese-bank';
import { ADDITIONAL_VARIANTS } from './additional-bank';
import { YOUNG_ADULT_VARIANTS } from './young-adult-bank';
import { questionCoverage, withQuestionMetadata } from './question-metadata';
import { hasQuestionVisual } from './question-visual-index';
import { CONTENT } from './curriculum-content';
import type { EduItem } from './curriculum-types';

export const QUESTION_BANK:Record<string,Array<EduItem&{topic?:string}>>=Object.fromEntries(Object.entries(CONTENT).map(([id,unit])=>{const m=id.match(/^(.*)-N([1-5])$/)!;const variants=[...PORTUGUESE_VARIANTS,...ADDITIONAL_VARIANTS,...YOUNG_ADULT_VARIANTS];const extra=variants.filter(x=>x.skill===m[1]&&x.level==='N'+m[2]).map(x=>{const answer=x.kind==='choice'&&/^[a-e]$/i.test(String(x.answer||''))?x.options?.[String(x.answer).toLowerCase().charCodeAt(0)-97]||x.answer:x.answer;return{...x,answer,accept:[...(x.accept||[]),answer]};});return[id,extra];}));const supplementalPractice=(id:string):EduItem[]=>{const m=id.match(/^(.*)-N([1-5])$/);if(!m)return[];const skill=m[1],level=Number(m[2]);return Array.from({length:12},(_,i)=>{const s=i+1,a=8+level*3+i,b=2+level+(i%4),prefix='Situação '+s+': ';
if(skill==='leitura'){if(level===1){const word=['CASA','MESA','PORTA','CAIXA','LISTA','OBRA','TURNO','AVISO','EQUIPE','MATERIAL','REGISTRO','ENTREGA'][i];return{kind:'short-text',prompt:prefix+'na palavra '+word+', escreva a primeira letra.',answer:word[0],accept:[word[0].toLowerCase()],hint:'Observe a primeira letra da palavra.'}}if(level===2){const h=7+i;return{kind:'short-text',prompt:prefix+'no aviso “ENTREGA ÀS '+h+'H”, escreva somente o horário.',answer:String(h),accept:[String(h)+'h'],hint:'Localize o horário informado.'}}return{kind:'choice',prompt:prefix+(level===3?'na instrução “registre e depois assine”, qual ação vem primeiro?':level===4?'qual opção mantém a ordem “conferir antes de liberar”?':'duas mensagens discordam. Qual informação deve ser confirmada primeiro?'),options:level===3?['Registrar','Assinar','Encerrar']:level===4?['Conferir antes de liberar','Liberar antes de conferir','As duas ordens são iguais']:['A fonte oficial mais recente','A mensagem mais antiga','Qualquer mensagem sem conferir'],answer:level===3?'Registrar':level===4?'Conferir antes de liberar':'A fonte oficial mais recente',hint:'Leia a ordem e a confiabilidade das informações.'}}
if(skill==='compreensao')return{kind:'choice',prompt:prefix+(level<=2?'um aviso informa uma ação e um horário. O que deve ser identificado?':level<=4?'uma orientação tem etapas. O que ajuda a compreendê-la corretamente?':'duas fontes discordam. O que ajuda a decidir?'),options:level<=2?['A ação e o horário','Somente a cor','Um dado que não aparece']:level<=4?['A ordem e os dados explícitos','Ignorar uma etapa','Trocar a instrução']:['Fonte, data e evidência','A opinião mais rápida','A mensagem mais antiga'],answer:level<=2?'A ação e o horário':level<=4?'A ordem e os dados explícitos':'Fonte, data e evidência',hint:'Use somente as informações que podem ser verificadas.'};
if(skill==='escrita')return{kind:'choice',prompt:prefix+'qual registro está mais adequado para uma comunicação de trabalho?',options:level<=2?['Material em falta no setor.','Deu ruim.','Uma coisa aí.']:level<=4?['12/03 · setor A · 4 peças entregues.','Resolvido.','Foi feito algo.']:['Repor 8 peças porque o saldo registrado ficou abaixo da necessidade.','Comprar porque sim.','Sempre fizemos assim.'],answer:level<=2?'Material em falta no setor.':level<=4?'12/03 · setor A · 4 peças entregues.':'Repor 8 peças porque o saldo registrado ficou abaixo da necessidade.',hint:'Prefira informação clara e verificável.'};
if(skill==='adicao')return{kind:'short-text',prompt:prefix+'havia '+a+' peças e entraram mais '+b+'. Quantas há agora?',answer:String(a+b),accept:[],hint:'Some as duas quantidades.'};
if(skill==='multiplicacao'){const g=2+level+(i%3),q=2+level+(i%4);return{kind:'short-text',prompt:prefix+g+' grupos têm '+q+' itens cada. Quantos itens há ao todo?',answer:String(g*q),accept:[],hint:'Multiplique grupos por itens em cada grupo.'}}
if(skill==='divisao'){const d=2+level+(i%3),q=2+level+(i%4),total=d*q;return{kind:'short-text',prompt:prefix+total+' itens serão divididos igualmente entre '+d+' pessoas. Quantos cada pessoa recebe?',answer:String(q),accept:[],hint:'Divida o total pela quantidade de pessoas.'}}
if(skill==='porcentagem'){const rates=[10,20,25,50,5],rate=rates[(i+level)%rates.length],base=rate===25?40*(1+(i%4)):rate===5?100*(1+(i%4)):50*(1+(i%4));return{kind:'short-text',prompt:prefix+'calcule '+rate+'% de '+base+'.',answer:String(base*rate/100),accept:[],hint:'Aplique o percentual ao valor informado.'}}
if(skill==='medidas'){const v=2+(i%8);return level<=2?{kind:'short-text',prompt:prefix+v+' metro(s) correspondem a quantos centímetros?',answer:String(v*100),accept:[String(v*100)+' cm'],hint:'Cada metro tem 100 centímetros.'}:{kind:'short-text',prompt:prefix+(v*100)+' centímetros correspondem a quantos metros?',answer:String(v),accept:[String(v)+' m'],hint:'Divida os centímetros por 100.'}}
if(skill==='seguranca')return{kind:'choice',prompt:prefix+'ao perceber uma condição de risco, qual conduta é mais adequada?',options:['Interromper com segurança, sinalizar e comunicar','Ignorar','Esconder o risco'],answer:'Interromper com segurança, sinalizar e comunicar',hint:'Priorize prevenção e comunicação.'};
if(skill==='direitos')return{kind:'choice',prompt:prefix+'uma orientação ficou confusa. Qual atitude é mais adequada?',options:['Pedir esclarecimento e confirmar entendimento','Fingir que entendeu','Alterar sozinho'],answer:'Pedir esclarecimento e confirmar entendimento',hint:'Busque informação clara e respeitosa.'};
if(skill==='saude')return{kind:'choice',prompt:prefix+'uma pessoa relata mal-estar durante a atividade. O que fazer primeiro?',options:['Parar com segurança e buscar apoio','Mandar continuar','Esconder o sintoma'],answer:'Parar com segurança e buscar apoio',hint:'Priorize cuidado e comunicação.'};
return{kind:'choice',prompt:prefix+'uma mensagem desconhecida pede sua senha. O que fazer?',options:['Não enviar e confirmar a origem','Enviar imediatamente','Publicar a senha'],answer:'Não enviar e confirmar a origem',hint:'Proteja seus dados e confirme a origem.'};
})};
export const selectQuestions=(id:string,base:EduItem[],seed=Date.now(),requested=base.length,preferVisual=false)=>{const pool=[...base,...(QUESTION_BANK[id]||[]),...supplementalPractice(id)],target=Math.max(1,Math.min(pool.length,Math.floor(requested||base.length)));let n=seed>>>0;const ranked=pool.map((item,index)=>({item,index,key:(n=(n*1664525+1013904223+index)>>>0),visual:hasQuestionVisual(item.prompt)?1:0})).sort((a,b)=>preferVisual&&a.visual!==b.visual?b.visual-a.visual:a.key-b.key),maxOpen=Math.max(1,Math.ceil(target/6)),selected:EduItem[]=[],seen=new Set<string>();let openResponses=0;for(const candidate of ranked){const key=candidate.item.prompt.normalize('NFKC').trim().toLocaleLowerCase('pt-BR').replace(/\s+/g,' ');if(seen.has(key)||candidate.item.kind==='text'&&openResponses>=maxOpen)continue;selected.push(candidate.item);seen.add(key);if(candidate.item.kind==='text')openResponses+=1;if(selected.length===target)break}if(selected.length<target){for(const candidate of ranked){const key=candidate.item.prompt.normalize('NFKC').trim().toLocaleLowerCase('pt-BR').replace(/\s+/g,' ');if(seen.has(key))continue;selected.push(candidate.item);seen.add(key);if(selected.length===target)break}}return selected.map((item,index)=>withQuestionMetadata(id,item,index))};export const QUESTION_COVERAGE=Object.fromEntries(Object.entries(CONTENT).map(([id,unit])=>{const sample=selectQuestions(id,unit.items,20260827,13),coverage=questionCoverage(sample);return[id,{...coverage,ok:coverage.unique>=13&&coverage.part1>=3&&coverage.part2>=6&&coverage.review>=4}]}));

