import { auth, api } from './cloudflare-client';

type Company = {id:string;name:string;adminEmail:string;status:string;reserved?:boolean;modules:string[];channels:string[];passwordCreatedAt?:string;usersCount:number;projectsCount:number;devicesCount:number;license?:{id:string;plan?:string;expiresAt?:string;code?:string};users?:Array<{email:string;name?:string;role?:string}>;projects?:Array<{name:string}>;devices?:Array<{name:string;status:string}>};
type DeboraLicenseResponse={state?:string;activation?:string;grant?:{email?:string;status?:string;expires_at?:string;plan_code?:string}|null};
const modules=['finance','rh','contracts','rdo','obra360','dre','procurement','measurements','documents','universidade','ai'];
const labels:Record<string,string>={finance:'Financeiro',rh:'RH',contracts:'Contratos',rdo:'RDO',obra360:'Obra360',dre:'DRE',procurement:'Compras',measurements:'Medições',documents:'Documentos',universidade:'Universidade',ai:'IA',desktop:'Desktop',mobile:'Web / mobile'};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]!));
const root=()=>document.getElementById('content')!;
const message=(e:unknown)=>(e as {message?:string}).message||'Não foi possível concluir.';
const state=(c:Company)=>c.status==='expired'?'Vencida':c.status==='suspended'||c.status==='revoked'?'Suspensa':c.status==='active'?'Ativa':'Aguardando ativação';
function choices(name:string,items:string[],selected:string[]){return items.map(k=>`<label class="check"><input type="checkbox" name="${name}" value="${k}" ${selected.includes(k)?'checked':''}>${labels[k]||k}</label>`).join('')}
function selected(form:HTMLFormElement,name:string){return [...form.querySelectorAll<HTMLInputElement>(`input[name="${name}"]:checked`)].map(x=>x.value)}
function header(){return `<div class="owner-head"><div><small>SUPERADMIN ARTISYS</small><h1>Central Artisys</h1><p>Clientes e empresas independentes. Cada empresa tem seus próprios usuários, obras e dispositivos.</p></div><div class="owner-head-actions"><a class="linkbtn" href="./index.html#portal">Minha operação</a><button id="centralLogout" class="linkbtn">Sair</button></div></div>`}
function logout(){document.getElementById('centralLogout')?.addEventListener('click',async()=>{await auth.signOut();location.href='./index.html'})}
function showOwnerLogin(){
  root().innerHTML=`<section class="auth-page"><div class="auth-card"><h1>Central Artisys</h1><p>Gestão de empresas. Acesso exclusivo do superadmin.</p><form id="centralLogin"><label>E-mail<input name="email" type="email" autocomplete="username" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" required></label><button class="btn" type="submit">Entrar</button><p id="centralLoginResult" role="status"></p></form></div></section>`;
  const form=document.getElementById('centralLogin') as HTMLFormElement,result=document.getElementById('centralLoginResult')!;
  form.onsubmit=async e=>{e.preventDefault();const values=new FormData(form),button=form.querySelector<HTMLButtonElement>('button[type="submit"]')!;button.disabled=true;result.textContent='Entrando…';try{await api.post('/api/auth/password/login',{email:String(values.get('email')||'').trim(),password:String(values.get('password')||'')});location.reload()}catch(error){result.textContent=message(error);button.disabled=false}};
}
function deboraLicenseCard(){return `<section class="card"><h2>Débora Lactação — Pro 6 meses</h2><p>Liberação manual para vendas externas. O e-mail abaixo identifica somente a conta da cliente; seu acesso de superadmin da Central permanece separado.</p><form id="deboraLicenseForm"><div class="form"><label>E-mail da cliente<input name="email" type="email" required autocomplete="off" placeholder="cliente@exemplo.com"></label></div><div class="owner-head-actions"><button class="btn" type="submit">Liberar 6 meses</button><button class="linkbtn" type="button" id="deboraLicenseStatus">Consultar</button><button class="linkbtn" type="button" id="deboraLicenseRevoke">Revogar</button></div><p id="deboraLicenseResult" role="status"></p></form></section>`}
function describeDeboraLicense(data:DeboraLicenseResponse){
  if(!data.grant)return data.state==='none'?'Nenhuma licença manual encontrada para este e-mail.':'Operação concluída.';
  const expires=data.grant.expires_at?new Date(data.grant.expires_at).toLocaleDateString('pt-BR'):'—';
  const status=data.state||data.grant.status||data.activation||'atualizada';
  const activation=data.activation&&data.activation!==status?` · ativação: ${data.activation}`:'';
  return `Licença ${status}${activation} · validade: ${expires}.`;
}
function bindDeboraLicense(){
  const form=document.getElementById('deboraLicenseForm') as HTMLFormElement|null,result=document.getElementById('deboraLicenseResult');
  if(!form||!result)return;
  const email=()=>String(new FormData(form).get('email')||'').trim();
  const run=async(action:'grant'|'status'|'revoke',button:HTMLButtonElement)=>{button.disabled=true;result.textContent=action==='grant'?'Liberando acesso...':'Consultando licença...';try{const {data}=await api.post<DeboraLicenseResponse>('/api/owner/debora-license',{action,email:email()});result.textContent=describeDeboraLicense(data)}catch(error){result.textContent=message(error)}finally{button.disabled=false}};
  form.onsubmit=e=>{e.preventDefault();void run('grant',form.querySelector<HTMLButtonElement>('button[type="submit"]')!)};
  const status=document.getElementById('deboraLicenseStatus') as HTMLButtonElement|null,revoke=document.getElementById('deboraLicenseRevoke') as HTMLButtonElement|null;
  if(status)status.onclick=()=>void run('status',status);
  if(revoke)revoke.onclick=()=>void run('revoke',revoke);
}
async function detail(id:string){
  const {data}=await api.get<{company:Company}>(`/api/owner/companies/${encodeURIComponent(id)}`),c=data.company;
  root().innerHTML=header()+`<button id="backCompanies" class="linkbtn">← Todas as empresas</button><section class="card"><h2>${esc(c.name)}</h2><p>${state(c)} · Admin principal: ${esc(c.adminEmail)}</p><p>Senha criada: ${c.passwordCreatedAt?esc(c.passwordCreatedAt):'Aguardando primeiro acesso por desktop ou web'}</p><p>Plano: ${esc(c.license?.plan||'Manual')} · Validade: ${esc(c.license?.expiresAt||'Sem vencimento')}</p><p>Empresa: ${esc(c.id)}</p></section><form id="licenseForm" class="card"><h2>Licença da empresa</h2><h3>Módulos</h3><div class="owner-grid">${choices('modules',modules,c.modules)}</div><h3>Canais</h3>${choices('channels',['desktop','mobile'],c.channels)}<label>Status<select name="status"><option value="active" ${state(c)!=='Suspensa'?'selected':''}>Liberada</option><option value="suspended" ${state(c)==='Suspensa'?'selected':''}>Suspensa</option></select></label><button class="btn">Salvar licença</button><p role="status" id="licenseResult"></p></form><section class="card"><h2>Usuários desta empresa</h2><p>Os usuários internos são administrados pelo responsável dentro da operação desta empresa.</p>${(c.users||[]).map(u=>`<p>${esc(u.name||u.email)} · ${esc(u.email)} · ${esc(u.role||'')}</p>`).join('')||'<p>Nenhum usuário ativado.</p>'}</section><section class="card"><h2>Obras</h2>${(c.projects||[]).map(p=>`<p>${esc(p.name)}</p>`).join('')||'<p>Nenhuma obra cadastrada.</p>'}</section><section class="card"><h2>Dispositivos</h2>${(c.devices||[]).map(d=>`<p>${esc(d.name)} · ${esc(d.status)}</p>`).join('')||'<p>Nenhum desktop ativado.</p>'}</section>`;
  logout();document.getElementById('backCompanies')!.onclick=()=>void render();
  document.getElementById('licenseForm')!.onsubmit=async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement,button=form.querySelector('button')!;button.disabled=true;try{await api.put(`/api/owner/companies/${encodeURIComponent(id)}`,{modules:selected(form,'modules'),channels:selected(form,'channels'),status:new FormData(form).get('status')});document.getElementById('licenseResult')!.textContent='Licença atualizada.'}catch(error){document.getElementById('licenseResult')!.textContent=message(error)}finally{button.disabled=false}};
}
async function render(){
  document.querySelector('.nav')?.setAttribute('style','display:none'); document.querySelector('.top')?.setAttribute('style','display:none'); document.title='Central Artisys — Empresas clientes';
  if(!await auth.hasSession()){showOwnerLogin();return}
  try{const {data}=await api.get<{companies:Company[]}>('/api/owner/companies');root().innerHTML=header()+deboraLicenseCard()+`<section class="card"><h2>Criar empresa cliente</h2><p>Cria uma licença e uma empresa independente. O admin define a senha no primeiro acesso, inclusive diretamente no desktop.</p><form id="companyForm"><div class="form"><label>Empresa<input name="name" required maxlength="120"></label><label>E-mail do admin principal<input name="adminEmail" type="email" required></label><label>Plano<input name="plan" value="manual" required></label></div><h3>Módulos contratados</h3><div class="owner-grid">${choices('modules',modules,modules)}</div><h3>Canais</h3>${choices('channels',['desktop','mobile'],['desktop','mobile'])}<button class="btn">Criar empresa e código de liberação</button><p id="createResult" role="status"></p></form></section><section class="section"><h2>Empresas clientes</h2><p>${data.companies.length} empresa(s) e licença(s) reservada(s)</p><div id="companyList">${data.companies.map(c=>`<article class="card"><h3>${esc(c.name)}</h3><p>${esc(c.adminEmail)} · ${state(c)}</p><p>${esc(c.license?.plan||'Manual')} · ${c.usersCount} usuário(s) · ${c.projectsCount} obra(s) · ${c.devicesCount} dispositivo(s)</p><p>${c.modules.map(m=>esc(labels[m]||m)).join(' · ')}</p><button class="linkbtn" data-company="${esc(c.id)}">Ver empresa e licença</button></article>`).join('')||'<p>Nenhuma empresa cliente.</p>'}</div></section>`;logout();bindDeboraLicense();
    document.querySelectorAll<HTMLButtonElement>('[data-company]').forEach(b=>b.onclick=()=>void detail(b.dataset.company!).catch(e=>alert(message(e))));
    document.getElementById('companyForm')!.onsubmit=async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement,button=form.querySelector('button')!,values=new FormData(form);button.disabled=true;try{const {data}=await api.post('/api/owner/companies',{name:values.get('name'),adminEmail:values.get('adminEmail'),plan:values.get('plan'),modules:selected(form,'modules'),channels:selected(form,'channels')});await render();const result=document.getElementById('createResult')!;result.textContent=`Empresa criada. E-mail: ${values.get('adminEmail')}. Código de primeiro acesso: ${data.license.code}. Guarde o código e entregue ao admin principal.`}catch(error){document.getElementById('createResult')!.textContent=message(error)}finally{button.disabled=false}};
  }catch(e){root().innerHTML=`<section class="card"><h1>Central Artisys</h1><p>${esc(message(e))}</p><a href="./index.html#portal">Voltar à minha operação</a></section>`}
}
export function mountOwnerPortal(){void render()}
