type OwnerApi={get:<T=any>(path:string,query?:Record<string,unknown>)=>Promise<{data:T}>;post:<T=any>(path:string,body?:unknown)=>Promise<{data:T}>};
type Partner={id:string;name:string;code:string;partner_type?:string;active?:number|boolean;commission_type?:string;commission_value?:number;discount_type?:string;discount_value?:number};
type PartnerSale={id:string;partner_code_snapshot?:string;plan_code?:string;status?:string;commission_status?:string;total_cents?:number;discount_cents?:number;commission_cents?:number;created_at?:string;partners?:{name?:string}|null};
let currentPartners:Partner[]=[];
let activeApi:OwnerApi|null=null;
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const money=(cents:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(cents||0)/100);
const rule=(type?:string,value?:number)=>type==='percent'?`${Number(value||0)}%`:type==='fixed'?money(Number(value||0)*100):'—';

export function deboraPartnersSection(){return `<section class="owner-section" data-debora-partners-root>
  <div class="owner-section-head"><div><span class="owner-eyebrow">PARCEIROS E CUPONS</span><h2>Parceiros, descontos e comissões</h2><p>Os códigos abaixo são os mesmos usados pelo checkout da Débora. Nenhum dado é duplicado na Central.</p></div></div>
  <p data-debora-partners-status role="status">Carregando parceiros…</p>
  <form class="owner-form-grid" data-debora-partner-form>
    <input type="hidden" name="id">
    <label>Nome<input name="name" required maxlength="160"></label>
    <label>Código / cupom<input name="code" required maxlength="64" pattern="[A-Za-z0-9_-]{2,64}" placeholder="ANA15"></label>
    <label>Tipo<select name="partnerType"><option value="partner">Parceiro</option><option value="influencer">Influenciador</option><option value="campaign">Campanha</option></select></label>
    <label>Comissão<select name="commissionType"><option value="none">Sem comissão</option><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select></label>
    <label>Valor da comissão<input name="commissionValue" type="number" min="0" step="0.01" value="0"></label>
    <label>Desconto<select name="discountType"><option value="none">Sem desconto</option><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select></label>
    <label>Valor do desconto<input name="discountValue" type="number" min="0" step="0.01" value="0"></label>
    <label><input name="active" type="checkbox" checked> Código ativo</label>
    <div class="owner-actions"><button class="owner-primary" type="submit">Salvar parceiro</button><button class="owner-secondary" type="button" data-debora-partner-reset>Limpar</button></div>
  </form>
  <div class="owner-debora-table-wrap"><table class="owner-debora-table"><thead><tr><th>Parceiro</th><th>Código</th><th>Desconto</th><th>Comissão</th><th>Status</th><th></th></tr></thead><tbody data-debora-partners-body></tbody></table></div>
  <h3>Vendas atribuídas</h3>
  <div data-debora-partner-summary></div>
  <div class="owner-debora-table-wrap"><table class="owner-debora-table"><thead><tr><th>Data</th><th>Parceiro</th><th>Plano</th><th>Total</th><th>Desconto</th><th>Comissão</th><th>Status</th><th></th></tr></thead><tbody data-debora-partner-sales-body></tbody></table></div>
</section>`}

function resetForm(){const form=document.querySelector<HTMLFormElement>('[data-debora-partner-form]');if(!form)return;form.reset();(form.elements.namedItem('id') as HTMLInputElement).value='';(form.elements.namedItem('commissionValue') as HTMLInputElement).value='0';(form.elements.namedItem('discountValue') as HTMLInputElement).value='0';(form.elements.namedItem('active') as HTMLInputElement).checked=true}
function editPartner(id:string){const partner=currentPartners.find(item=>item.id===id),form=document.querySelector<HTMLFormElement>('[data-debora-partner-form]');if(!partner||!form)return;(form.elements.namedItem('id') as HTMLInputElement).value=partner.id;(form.elements.namedItem('name') as HTMLInputElement).value=partner.name;(form.elements.namedItem('code') as HTMLInputElement).value=partner.code;(form.elements.namedItem('partnerType') as HTMLSelectElement).value=partner.partner_type||'partner';(form.elements.namedItem('commissionType') as HTMLSelectElement).value=partner.commission_type||'none';(form.elements.namedItem('commissionValue') as HTMLInputElement).value=String(partner.commission_value??0);(form.elements.namedItem('discountType') as HTMLSelectElement).value=partner.discount_type||'none';(form.elements.namedItem('discountValue') as HTMLInputElement).value=String(partner.discount_value??0);(form.elements.namedItem('active') as HTMLInputElement).checked=Number(partner.active)===1||partner.active===true;form.scrollIntoView?.({behavior:'smooth',block:'start'})}

async function loadPartners(){if(!activeApi)return;const {data}=await activeApi.get<{partners:Partner[]}>('/api/owner/debora-partners');currentPartners=data.partners||[];const body=document.querySelector<HTMLElement>('[data-debora-partners-body]');if(body)body.innerHTML=currentPartners.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.code)}</td><td>${esc(rule(p.discount_type,p.discount_value))}</td><td>${esc(rule(p.commission_type,p.commission_value))}</td><td>${Number(p.active)===1||p.active===true?'Ativo':'Inativo'}</td><td><button class="owner-secondary" type="button" data-debora-edit-partner="${esc(p.id)}">Editar</button></td></tr>`).join('')||'<tr><td colspan="6">Nenhum parceiro cadastrado.</td></tr>';document.querySelectorAll<HTMLButtonElement>('[data-debora-edit-partner]').forEach(button=>button.onclick=()=>editPartner(button.dataset.deboraEditPartner||''))}
async function loadSales(){if(!activeApi)return;const {data}=await activeApi.get<{summary?:Record<string,number>;sales:PartnerSale[]}>('/api/owner/debora-partner-sales');const summary=data.summary||{},summaryEl=document.querySelector<HTMLElement>('[data-debora-partner-summary]');if(summaryEl)summaryEl.innerHTML=`<p>Vendas pagas: <strong>${Number(summary.paidSales||0)}</strong> · Receita atribuída: <strong>${esc(money(summary.revenueCents))}</strong> · Descontos: <strong>${esc(money(summary.discountCents))}</strong> · Comissão pendente: <strong>${esc(money(summary.pendingCommissionCents))}</strong></p>`;const body=document.querySelector<HTMLElement>('[data-debora-partner-sales-body]'),sales=data.sales||[];if(body)body.innerHTML=sales.map(s=>`<tr><td>${esc(s.created_at?new Date(s.created_at).toLocaleString('pt-BR'):'—')}</td><td>${esc(s.partners?.name||s.partner_code_snapshot||'—')}</td><td>${esc(s.plan_code||'—')}</td><td>${esc(money(s.total_cents))}</td><td>${esc(money(s.discount_cents))}</td><td>${esc(money(s.commission_cents))}</td><td>${esc(`${s.status||'—'} / ${s.commission_status||'—'}`)}</td><td>${s.status==='paid'&&s.commission_status==='pending'?`<button class="owner-secondary" type="button" data-debora-approve-commission="${esc(s.id)}">Aprovar comissão</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="8">Nenhuma venda atribuída.</td></tr>';document.querySelectorAll<HTMLButtonElement>('[data-debora-approve-commission]').forEach(button=>button.onclick=async()=>{await activeApi!.post('/api/owner/debora-partner-commission',{attributionId:button.dataset.deboraApproveCommission});await loadSales()})}

export async function refreshDeboraPartners(){await Promise.all([loadPartners(),loadSales()])}
export async function bindDeboraPartners(api:OwnerApi){const root=document.querySelector('[data-debora-partners-root]');if(!root)return;activeApi=api;const status=document.querySelector<HTMLElement>('[data-debora-partners-status]');const form=document.querySelector<HTMLFormElement>('[data-debora-partner-form]');document.querySelector<HTMLButtonElement>('[data-debora-partner-reset]')!.onclick=resetForm;if(form)form.onsubmit=async event=>{event.preventDefault();const values=new FormData(form),payload={id:String(values.get('id')||'')||undefined,name:String(values.get('name')||'').trim(),code:String(values.get('code')||'').trim().toUpperCase(),partnerType:String(values.get('partnerType')||'partner'),commissionType:String(values.get('commissionType')||'none'),commissionValue:Number(values.get('commissionValue')||0),discountType:String(values.get('discountType')||'none'),discountValue:Number(values.get('discountValue')||0),active:Boolean(values.get('active'))};await api.post('/api/owner/debora-partners',payload);resetForm();await refreshDeboraPartners()};try{await refreshDeboraPartners();if(status)status.textContent='Parceiros e vendas atribuídas atualizados.'}catch(error){if(status)status.textContent=`Parceiros indisponíveis: ${error instanceof Error?error.message:'erro de comunicação'}`}}
