import { api } from './cloudflare-client';
import { CONTENT, T } from './curriculum';
import { learningStageForLevel } from './learning-stages';
import { buildLessonComposition } from './lesson-composition';
import { canTutorReroll, nextTutorUnit, tutorAttemptStatus } from './tutor-model';
import { evaluateLessonAnswer } from './lesson-feedback';
import { adminFailureDetail, adminGroupLabel, educationRoleLabel } from './admin-rh-model';

type AdminDeps={
  token:()=>string;
  render:(title:string,html:string,nav?:string)=>void;
  notify:(message:string)=>void;
  errorMessage:(error:unknown)=>string;
  canAccessAdmin:()=>boolean;
  canManageRoles:()=>boolean;
  onUnauthorized:()=>void;
  openTracks:()=>void;
};

const LEVELS=['N1','N2','N3','N4','N5'];
const allUnits=()=>T.flatMap(track=>LEVELS.map((level,index)=>({id:track[0]+'-'+level,t:track[0],n:track[1],i:track[2],l:level,k:index+1})));

export function createUniversityAdminUi(deps:AdminDeps){
function rhLoading(){deps.render('Tutor','<article class="edu-card"><h1>Carregando Tutor…</h1><p>Aguarde enquanto carregamos o acompanhamento dos colaboradores.</p></article>','admin')}
function rhFailure(x:unknown){const detail=adminFailureDetail(x);deps.render('Tutor','<article class="edu-card"><h1>Não foi possível abrir o Tutor</h1><p>'+detail+'</p><button id="retryRh" class="edu-primary">Tentar novamente</button></article>','admin');document.getElementById('retryRh')?.addEventListener('click',()=>void showRh())}
async function showRh(){rhLoading();try{await rh()}catch(x){rhFailure(x)}}
async function tutorParticipant(participantId:string){
 if(!deps.canAccessAdmin())return deps.onUnauthorized();
 const data=(await api.post('/api/edu/admin/participant',{token:deps.token(),participantId})).data,person=data.participant;
 const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char));
 const tutorUnits=allUnits().filter(unit=>CONTENT[unit.id]).map(unit=>({id:unit.id,competency:unit.t,level:unit.l,title:unit.n})),next=nextTutorUnit(person,tutorUnits);
 const competencies=T.map(track=>{const level=person.skillLevels?.[track[0]]||'N1',confidence=Math.round(Number(person.skillConfidence?.[track[0]]||.55)*100),stage=learningStageForLevel(level);return'<article class="edu-tutor-skill"><b>'+esc(String(track[1]))+'</b><span>'+stage.label+'</span><small>'+esc(level)+' interno · confiança '+confidence+'%</small></article>'}).join('');
 const attempts=(data.lessonAttempts||[]) as Array<{id:string;unit:string;seed:number;questionIds:string[];reinforcementQuestionIds:string[];responseCount:number;status:string;preparedBy:string;createdAt:string;completedAt?:string;rerollCount:number}>,active=attempts.find(item=>item.status!=='completed'),history=attempts.filter(item=>item.status==='completed').slice(0,8);
 let preparedHtml='<p>Nenhuma aula preparada.</p>';
 if(active){let preview='';try{const composition=buildLessonComposition(active.unit,active.seed,active.selectionVersion||1);preview='<details><summary>Ver questões preparadas</summary><ol>'+[...composition.mainQuestions,...composition.reviewQuestions].map(item=>'<li>'+esc(item.prompt)+'</li>').join('')+'</ol></details>'}catch{} preparedHtml='<article class="edu-card edu-prepared-lesson"><small>'+tutorAttemptStatus(active.status,active.responseCount).toUpperCase()+'</small><h3>'+esc(active.unit.replace(/-N[1-5]$/,''))+' · '+learningStageForLevel(active.unit.match(/N[1-5]$/)?.[0]).label+'</h3><p>'+active.questionIds.length+' questões congeladas · '+active.responseCount+' respondida(s)</p>'+preview+'<div class="level-actions"><button class="edu-secondary" data-print-attempt="'+esc(active.id)+'">Imprimir aula</button><button class="edu-secondary" data-paper-attempt="'+esc(active.id)+'">Lançar respostas do papel</button></div>'+(canTutorReroll(active.status,active.responseCount)?'<button class="edu-secondary" data-reroll-attempt="'+esc(active.id)+'">Sortear outra aula</button>':'<p class="edu-lock-note">Sorteio bloqueado após a primeira resposta.</p>')+'</article>'}
 const historyHtml=history.map(item=>'<li><b>'+esc(item.unit.replace(/-N[1-5]$/,''))+'</b> · '+learningStageForLevel(item.unit.match(/N[1-5]$/)?.[0]).label+' · '+(item.completedAt?new Date(item.completedAt).toLocaleDateString('pt-BR'):'concluída')+'</li>').join('');
 deps.render('Tutor · '+person.name,'<div class="edu-page-head"><button id="backTutor" class="edu-back">← Colaboradores</button><small>ACOMPANHAMENTO INDIVIDUAL</small><h1>'+esc(person.name)+'</h1><p>'+esc(person.email||'')+'</p></div><section class="edu-tutor-overview"><article class="edu-card"><small>PRÓXIMA AULA SUGERIDA</small><h2>'+(next?esc(next.title)+' · '+learningStageForLevel(next.level).label:'Jornada concluída')+'</h2><p>'+(next?'Motor interno: '+esc(next.level)+'. O colaborador continua vendo apenas o Aprendizado.':'Não há nova unidade pendente.')+'</p>'+(next&&!active?'<button id="prepareTutorLesson" class="edu-primary" data-unit="'+esc(next.id)+'">Preparar próxima aula</button>':'')+'</article><article class="edu-card"><small>PROGRESSO</small><h2>'+(person.completedUnits?.length||0)+' de 60 unidades</h2><p>'+(data.pendingReviews?.length||0)+' resposta(s) aguardando correção.</p></article></section><section><h2>Perfil pedagógico</h2><div class="edu-tutor-skills">'+competencies+'</div></section><section><h2>Aula atual / preparada</h2>'+preparedHtml+'</section><details class="edu-admin-section"><summary>Histórico de aulas</summary><ul class="edu-history-list">'+(historyHtml||'<li>Nenhuma aula concluída ainda.</li>')+'</ul></details>','admin');
 document.getElementById('backTutor')?.addEventListener('click',()=>void showRh());
 document.getElementById('prepareTutorLesson')?.addEventListener('click',async event=>{const unit=(event.currentTarget as HTMLElement).dataset.unit||'';try{let attempt=(await api.post('/api/edu/admin/attempt/prepare',{token:deps.token(),participantId,unit})).data.attempt;const composition=buildLessonComposition(unit,attempt.seed,attempt.selectionVersion||1);attempt=(await api.post('/api/edu/admin/attempt/freeze',{token:deps.token(),participantId,attemptId:attempt.id,questionIds:composition.questionIds,reinforcementQuestionIds:composition.reinforcementQuestionIds})).data.attempt;deps.notify('Aula preparada.');await tutorParticipant(participantId)}catch(error){deps.notify(deps.errorMessage(error))}});
 document.querySelectorAll<HTMLElement>('[data-print-attempt]').forEach(button=>button.addEventListener('click',()=>{const selected=attempts.find(item=>item.id===button.dataset.printAttempt);if(!selected)return;const composition=buildLessonComposition(selected.unit,selected.seed,selected.selectionVersion||1),questions=[...composition.mainQuestions,...composition.reviewQuestions],stage=learningStageForLevel(selected.unit.match(/N[1-5]$/)?.[0]);deps.render('Imprimir aula','<section class="edu-print-sheet"><header><h1>Universidade Empresarial</h1><p><b>Colaborador:</b> '+esc(person.name)+' &nbsp; <b>Data:</b> ____/____/______</p><p><b>'+esc(selected.unit.replace(/-N[1-5]$/,''))+'</b> · '+stage.label+'</p></header><ol>'+questions.map((item,index)=>'<li><p>'+esc(item.prompt)+'</p>'+(item.options?.length?'<div class="edu-print-options">'+item.options.map(option=>'□ '+esc(option)).join('<br>')+'</div>':'<div class="edu-print-lines">__________________________________________________<br>__________________________________________________</div>')+'</li>').join('')+'</ol></section><div class="edu-no-print level-actions"><button id="doPrint" class="edu-primary">Imprimir</button><button id="backFromPrint" class="edu-secondary">Voltar</button></div>','admin');document.getElementById('doPrint')?.addEventListener('click',()=>window.print());document.getElementById('backFromPrint')?.addEventListener('click',()=>void tutorParticipant(participantId))}));
 document.querySelectorAll<HTMLElement>('[data-paper-attempt]').forEach(button=>button.addEventListener('click',()=>{const selected=attempts.find(item=>item.id===button.dataset.paperAttempt);if(!selected)return;const composition=buildLessonComposition(selected.unit,selected.seed),questions=[...composition.mainQuestions,...composition.reviewQuestions],answered=new Set((selected.responses||[]).map(item=>item.questionId));deps.render('Respostas do papel','<div class="edu-page-head"><button id="backPaper" class="edu-back">← Voltar</button><small>PONTE PAPEL → ONLINE</small><h1>Lançar respostas do papel</h1><p>Somente questões ainda sem resposta podem ser registradas.</p></div><form id="paperForm" class="edu-paper-entry">'+questions.map((item,index)=>{const qid=item.meta?.id||'',locked=answered.has(qid);return'<article class="edu-card"><small>QUESTÃO '+(index+1)+'</small><p><b>'+esc(item.prompt)+'</b></p>'+(locked?'<p class="edu-lock-note">Já respondida. Não pode ser sobrescrita.</p>':item.options?.length?'<select data-paper-q="'+esc(qid)+'"><option value="">Selecione a resposta</option>'+item.options.map(option=>'<option>'+esc(option)+'</option>').join('')+'</select>':'<textarea data-paper-q="'+esc(qid)+'" placeholder="Transcreva a resposta do papel"></textarea>')+'</article>'}).join('')+'<button class="edu-primary">Salvar respostas preenchidas</button></form>','admin');document.getElementById('backPaper')?.addEventListener('click',()=>void tutorParticipant(participantId));document.getElementById('paperForm')?.addEventListener('submit',async event=>{event.preventDefault();const controls=Array.from((event.currentTarget as HTMLFormElement).querySelectorAll<HTMLSelectElement|HTMLTextAreaElement>('[data-paper-q]')).filter(control=>control.value.trim());if(!controls.length)return deps.notify('Preencha ao menos uma resposta.');try{for(const control of controls){const qid=control.dataset.paperQ||'',item=questions.find(question=>question.meta?.id===qid);if(!item)continue;const evaluation=evaluateLessonAnswer(item,control.value.trim());await api.post('/api/edu/admin/attempt/paper-response',{token:deps.token(),participantId,attemptId:selected.id,questionId:qid,response:control.value.trim(),correct:evaluation.correct})}deps.notify('Respostas do papel registradas.');await tutorParticipant(participantId)}catch(error){deps.notify(deps.errorMessage(error))}})}));
 document.querySelectorAll<HTMLElement>('[data-reroll-attempt]').forEach(button=>button.addEventListener('click',async()=>{try{let attempt=(await api.post('/api/edu/admin/attempt/reroll',{token:deps.token(),participantId,attemptId:button.dataset.rerollAttempt})).data.attempt;const composition=buildLessonComposition(attempt.unit,attempt.seed,attempt.selectionVersion||1);await api.post('/api/edu/admin/attempt/freeze',{token:deps.token(),participantId,attemptId:attempt.id,questionIds:composition.questionIds,reinforcementQuestionIds:composition.reinforcementQuestionIds});deps.notify('Nova composição preparada.');await tutorParticipant(participantId)}catch(error){deps.notify(deps.errorMessage(error))}}))
}
async function rh(){
 if(!deps.canAccessAdmin())return deps.onUnauthorized();
 const data=(await api.post('/api/edu/admin/overview',{token:deps.token()})).data,esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char));
 const actions=(data.actionParticipants||[]).map((person:{id:string;name:string;group:string;evidence:string;nextAction:string})=>'<button class="edu-action-card '+esc(person.group)+'" data-tutor-person="'+esc(person.id)+'"><small>'+esc(adminGroupLabel(person.group))+'</small><h3>'+esc(person.name)+'</h3><p>'+esc(person.evidence)+'</p><b>Próxima ação: '+esc(person.nextAction)+'</b></button>').join('');
 const pending=(data.pendingReviews||[]).map((review:{id:string;participantName?:string;skill?:string;level?:string;question?:string;response?:string})=>'<article class="review-item"><div><b>'+esc(review.participantName||'Colaborador')+'</b><small>'+esc(review.skill||'')+' · '+esc(review.level||'')+'</small><p><b>Pergunta:</b> '+esc(review.question||'')+'</p><p><b>Resposta:</b> '+esc(review.response||'')+'</p></div><div class="review-actions"><button class="edu-primary" data-review-id="'+esc(review.id)+'" data-review-action="approve">Aprovar</button><button class="edu-secondary" data-review-id="'+esc(review.id)+'" data-review-action="needs_revision">Solicitar revisão</button></div></article>').join('');
 const people=(data.participants||[]).map((person:{id:string;name:string;email?:string;role?:string;completedUnits?:string[];diagnosticCompletedAt?:string;preparedLesson?:{status:string}|null})=>{const role=String(person.role||'colaborador'),roleControl=deps.canManageRoles()?'<select aria-label="Perfil de '+esc(person.name)+'" data-role-id="'+esc(person.id)+'" data-role-current="'+esc(role)+'">'+['superadmin','admin','rh','gestor','colaborador'].map(value=>'<option value="'+value+'" '+(value===role?'selected':'')+'>'+educationRoleLabel(value)+'</option>').join('')+'</select>':educationRoleLabel(role);return'<tr><td><button class="edu-link-button" data-tutor-person="'+esc(person.id)+'">'+esc(person.name)+'</button></td><td>'+esc(person.email||'—')+'</td><td>'+roleControl+'</td><td>'+(person.completedUnits?.length||0)+'</td><td>'+(person.preparedLesson?'Aula '+esc(person.preparedLesson.status):person.diagnosticCompletedAt?'Pronto para aula':'Sondagem pendente')+'</td></tr>'}).join('');
 deps.render('Tutor','<section class="edu-page-head"><small>TUTOR</small><h1>Acompanhe cada colaborador</h1><p>Veja dificuldades, prepare a próxima aula, acompanhe tentativas e corrija respostas abertas.</p></section><section class="edu-action-grid">'+(actions||'<article class="edu-card"><p>Nenhuma ação urgente.</p></article>')+'</section><details class="edu-admin-section" open><summary>Respostas para corrigir ('+(data.pendingReviews?.length||0)+')</summary><div class="review-queue">'+(pending||'<p>Nenhuma resposta pendente.</p>')+'</div></details><details class="edu-admin-section" open><summary>Colaboradores</summary><div class="table-scroll"><table class="curriculum-table"><thead><tr><th>Colaborador</th><th>E-mail</th><th>Perfil</th><th>Unidades</th><th>Próxima situação</th></tr></thead><tbody>'+people+'</tbody></table></div></details><details class="edu-admin-section"><summary>Mapa curricular e biblioteca</summary><p>60 unidades · 12 competências · 3 áreas.</p><button id="all" class="edu-secondary">Abrir trilhas</button></details>','admin');
 document.querySelectorAll<HTMLElement>('[data-tutor-person]').forEach(button=>button.addEventListener('click',()=>void tutorParticipant(button.dataset.tutorPerson||'')));
 document.querySelectorAll<HTMLElement>('[data-review-id]').forEach(button=>button.addEventListener('click',async()=>{try{await api.post('/api/edu/admin/review',{token:deps.token(),reviewId:button.dataset.reviewId,action:button.dataset.reviewAction});await showRh()}catch(error){deps.notify(deps.errorMessage(error))}}));
 document.getElementById('all')?.addEventListener('click',deps.openTracks);
 document.querySelectorAll<HTMLSelectElement>('[data-role-id]').forEach(select=>select.addEventListener('change',async()=>{const before=select.dataset.roleCurrent||'colaborador';try{const response=await api.post('/api/edu/admin/role',{token:deps.token(),participantId:select.dataset.roleId,role:select.value});select.dataset.roleCurrent=response.data.participant.role}catch(error){select.value=before;deps.notify(deps.errorMessage(error))}}))
}

  return {open:showRh};
}
