import { db, error, json, runtimeEnv, type RouterRoutes } from '../cloudflare/sdk';
import { createLicense, mutateLicense, LICENSE_MODULES, LICENSE_CHANNELS } from './license-service';
import { createDeboraLicenseAdminRoutes } from './debora-license-admin';
import { createLojaOnlineAdminRoutes } from './loja-online-admin';
type Row=Record<string,any> & {id:string};
const norm=(v:unknown)=>String(v||'').trim().toLowerCase();
const limit=(value:unknown,fallback:number)=>Math.max(1,Math.min(999,Math.floor(Number(value)||fallback)));
async function rows(collection:string):Promise<Row[]>{const result=await runtimeEnv().DB.prepare('SELECT id,record_json FROM kv_records WHERE collection=?').bind(collection).all<{id:string;record_json:string}>();return(result.results||[]).map(r=>({...JSON.parse(r.record_json),id:r.id}));}
export function companyViews(companies:Row[],licenses:Row[],users:Row[],projects:Row[],devices:Row[],credentials:{email:string;created_at:string}[],ownerEmail:string,ownerCompanyName=""){
  const operationIds=new Set(companies.filter(c=>c.licenseId==='owner'||(!!ownerCompanyName&&norm(c.name)===norm(ownerCompanyName))||users.some(u=>u.platformRole==='superadmin'&&norm(u.email)===norm(ownerEmail)&&(u.companyIds||[]).includes(c.id))).map(c=>c.id));
  const view=(c:Row|undefined,l:Row|undefined)=>{const id=c?.id||`license:${l!.id}`,adminEmail=norm(c?.principalEmail||l?.email),us=users.filter(u=>(u.companyIds||[]).includes(id)&&u.platformRole!=='superadmin').map(u=>({id:u.id,email:u.email,name:u.name,status:u.status,role:u.email===adminEmail?'admin':'user',passwordCreatedAt:credentials.find(p=>norm(p.email)===norm(u.email))?.created_at||null})),ps=projects.filter(p=>p.companyId===id).map(p=>({id:p.id,name:p.name})),ds=devices.filter(d=>d.companyId===id).map(d=>({id:d.id,name:d.name,email:d.email,status:d.status,lastSeenAt:d.lastSeenAt}));const passwordCreatedAt=credentials.find(p=>norm(p.email)===adminEmail)?.created_at||null;return{id,name:c?.name||`Licença reservada — ${adminEmail||'sem e-mail'}`,adminEmail,reserved:!c,status:l?.status==='revoked'?'suspended':l?.expiresAt&&l.expiresAt<new Date().toISOString()?'expired':!l?.claimedBy?'pending':'active',license:l?{id:l.id,plan:l.plan,status:l.status,expiresAt:l.expiresAt,maxUsers:l.maxUsers,maxProjects:l.maxProjects,maxDevices:l.maxDevices,claimed:!!l.claimedBy}:null,modules:l?.modules||[],channels:l?.channels||[],passwordCreatedAt,usersCount:us.length,projectsCount:ps.length,devicesCount:ds.length,users:us,projects:ps,devices:ds};};
  return{companies:[...companies.filter(c=>!operationIds.has(c.id)).map(c=>view(c,licenses.find(l=>l.id===c.licenseId)||licenses.find(l=>l.companyId===c.id))),...licenses.filter(l=>!l.companyId&&!companies.some(c=>c.licenseId===l.id)&&norm(l.email)!==norm(ownerEmail)).map(l=>view(undefined,l))],operationCompanyIds:[...operationIds]};
}
async function inventory(){const [companies,licenses,users,projects,devices]=await Promise.all(['companies','licenses','platform_accesses','projects','devices'].map(rows));const table=await runtimeEnv().DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='password_credentials'").first();const credentials=table?(await runtimeEnv().DB.prepare('SELECT email,created_at FROM password_credentials').all<{email:string;created_at:string}>()).results||[]:[];return companyViews(companies,licenses,users,projects,devices,credentials,String(runtimeEnv().OWNER_EMAIL||''),String(runtimeEnv().OWNER_COMPANY||'Obra na Mão'));}
export function createCompanyRoutes(secured:RouterRoutes[string]):RouterRoutes{return{
 ...createDeboraLicenseAdminRoutes(secured),
 ...createLojaOnlineAdminRoutes(secured),
 'GET /api/owner/companies':[...secured,async()=>json(await inventory())],
 'GET /api/owner/companies/:id':[...secured,async(ctx)=>{const company=(await inventory()).companies.find(c=>c.id===ctx.params.id);return company?json({company}):error('Empresa não encontrada.',404)}],
 'POST /api/owner/companies':[...secured,async(ctx)=>{const b=(ctx.body||{}) as Row,name=String(b.name||'').trim(),email=norm(b.adminEmail),modules=(Array.isArray(b.modules)?b.modules:[]).filter((v:any)=>(LICENSE_MODULES as readonly string[]).includes(v)),channels=(Array.isArray(b.channels)?b.channels:[]).filter((v:any)=>(LICENSE_CHANNELS as readonly string[]).includes(v));if(!name||!/^\S+@\S+\.\S+$/.test(email)||!modules.length||!channels.length)return error('Informe empresa, e-mail do admin, módulos e canais.',400);if(email===norm(runtimeEnv().OWNER_EMAIL)||norm(name)===norm(runtimeEnv().OWNER_COMPANY||'Obra na Mão'))return error('Use uma empresa cliente e um administrador próprio.',409);const existing=await runtimeEnv().DB.prepare("SELECT id FROM kv_records WHERE (collection IN ('licenses','platform_accesses') AND lower(json_extract(record_json,'$.email'))=?) OR (collection='companies' AND lower(json_extract(record_json,'$.principalEmail'))=?) LIMIT 1").bind(email,email).first();if(existing)return error('Este e-mail já possui licença ou vínculo. Abra a empresa existente.',409);const stamp=new Date().toISOString(),companyId=crypto.randomUUID().replace(/-/g,''),companyRecord={name,principalEmail:email,createdAt:stamp,createdBy:ctx.user!.userId,tenantVersion:1,attendanceTimesheetMode:'disabled'};const inserted=await runtimeEnv().DB.prepare("INSERT INTO kv_records(collection,id,record_json,created_at,updated_at) SELECT 'companies',?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM kv_records WHERE (collection IN ('licenses','platform_accesses') AND lower(json_extract(record_json,'$.email'))=?) OR (collection='companies' AND lower(json_extract(record_json,'$.principalEmail'))=?) )").bind(companyId,JSON.stringify(companyRecord),stamp,stamp,email,email).run();if(Number(inserted.meta?.changes||0)!==1)return error('Este e-mail já foi reservado por outra criação.',409);const license=await createLicense({email,companyId,modules,channels,status:'active',plan:String(b.plan||'custom'),expiresAt:b.expiresAt||undefined,maxUsers:limit(b.maxUsers,10),maxProjects:limit(b.maxProjects,5),maxDevices:limit(b.maxDevices,2)},{source:'manual',userId:ctx.user!.userId,email:ctx.user!.email});await db.update('companies',[{id:companyId,record:{name,principalEmail:email,createdAt:stamp,createdBy:ctx.user!.userId,tenantVersion:1,attendanceTimesheetMode:'disabled',licenseId:license.id,licensedModules:modules,licensedChannels:channels}}]);const company=(await inventory()).companies.find(c=>c.id===companyId);return json({company,license},201)}],
 'PUT /api/owner/companies/:id':[...secured,async(ctx)=>{const company=(await inventory()).companies.find(c=>c.id===ctx.params.id);if(!company?.license)return error('Empresa ou licença não encontrada.',404);const b=(ctx.body||{}) as Row;const modules=(Array.isArray(b.modules)?b.modules:company.modules).filter((v:any)=>(LICENSE_MODULES as readonly string[]).includes(v)),channels=(Array.isArray(b.channels)?b.channels:company.channels).filter((v:any)=>(LICENSE_CHANNELS as readonly string[]).includes(v));if(!modules.length||!channels.length)return error('Selecione módulos e canais.',400);const license=await mutateLicense(company.license.id,l=>({...l,modules,channels,status:b.status==='suspended'?'revoked':b.status==='active'?'active':l.status,plan:b.plan!==undefined?String(b.plan||'custom'):l.plan,expiresAt:b.expiresAt===null||b.expiresAt===''?undefined:b.expiresAt!==undefined?String(b.expiresAt):l.expiresAt,maxUsers:b.maxUsers!==undefined?limit(b.maxUsers,l.maxUsers||10):l.maxUsers,maxProjects:b.maxProjects!==undefined?limit(b.maxProjects,l.maxProjects||5):l.maxProjects,maxDevices:b.maxDevices!==undefined?limit(b.maxDevices,l.maxDevices||2):l.maxDevices}),{source:'manual',userId:ctx.user!.userId,email:ctx.user!.email},'company_updated');return json({company:(await inventory()).companies.find(c=>c.id===ctx.params.id),license})}]
};}